### PR TITLE
GROW-1253

### PR DESCRIPTION
**Pull request by tamaspetrenko**
https://issues.liferay.com/browse/GROW-1253

### CODE REVIEW

**Comment by balcsida** [comment]
Hi @tamaspetrenko, @NemethNorbert and @CsabaTurcsan,

Can we delete the `_backup` folder and erase from the Git history as well?

Kind regards,
@balcsida

**Comment by CsabaTurcsan** [comment]
If we don't need it then yes @balcsida .
@tamaspetrenko  can you please run another git filter-branch rm? :D

**Comment by CsabaTurcsan** [comment]
Just started reviewing :)

**Comment by CsabaTurcsan** [comment]
Merged thx

**Pull request closed without merging**
